In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neural_network import MLPClassifier
import warnings
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')

In [ ]:
ins_df=pd.read_csv("/content/insurance_claimed_data.csv")

In [ ]:
ins_df.head()

Age Agency_Code           Type  Commision Channel  Duration  Sales  \
0   48         C2B       Airlines       0.70  Online         7   2.51   
1   36         EPX  Travel Agency       0.00  Online        34  20.00   
2   39         CWT  Travel Agency       5.94  Online         3   9.90   
3   36         EPX  Travel Agency       0.00  Online         4  26.00   
4   33         JZI       Airlines       6.30  Online        53  18.00   

  Destination Claimed       Product_Name  Claimed_Amount  
0        ASIA      No    Customised Plan               0  
1        ASIA      No    Customised Plan               0  
2    Americas      No    Customised Plan               0  
3        ASIA      No  Cancellation Plan               0  
4        ASIA      No        Bronze Plan               0

In [ ]:
ins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             3000 non-null   int64  
 1   Agency_Code     3000 non-null   object 
 2   Type            3000 non-null   object 
 3   Commision       3000 non-null   float64
 4   Channel         3000 non-null   object 
 5   Duration        3000 non-null   int64  
 6   Sales           3000 non-null   float64
 7   Destination     3000 non-null   object 
 8   Claimed         3000 non-null   object 
 9   Product_Name    3000 non-null   object 
 10  Claimed_Amount  3000 non-null   int64  
dtypes: float64(2), int64(3), object(6)
memory usage: 257.9+ KB


In [ ]:
print('Age \n',ins_df.Age.value_counts())
print('\n')
print('Agency_Code \n',ins_df.Agency_Code.value_counts())
print('\n')
print('Type \n',ins_df.Type.value_counts())
print('\n')
print('Commision \n',ins_df.Commision.value_counts())
print('\n')
print('Channel \n',ins_df.Channel.value_counts())
print('\n')
print('Duration \n',ins_df.Duration.value_counts())
print('\n')
print('Sales \n',ins_df.Sales.value_counts())
print('\n')
print('Claimed \n',ins_df.Claimed.value_counts())
print('\n')
print('Claimed Amount \n',ins_df.Claimed_Amount.value_counts())
print('\n')
print('Destination \n',ins_df.Destination.value_counts())
print('\n')
print('Claimed Amount \n',ins_df.Claimed_Amount.value_counts())

Age 
 Age
36    999
31    125
48    108
30     96
35     94
     ... 
8       1
84      1
83      1
15      1
11      1
Name: count, Length: 70, dtype: int64


Agency_Code 
 Agency_Code
EPX    1365
C2B     924
CWT     472
JZI     239
Name: count, dtype: int64


Type 
 Type
Travel Agency    1837
Airlines         1163
Name: count, dtype: int64


Commision 
 Commision
0.00     1366
63.21      62
23.76      61
54.00      61
17.82      57
         ... 
49.40       1
68.08       1
15.56       1
1.25        1
13.50       1
Name: count, Length: 324, dtype: int64


Channel 
 Channel
Online     2954
Offline      46
Name: count, dtype: int64


Duration 
 Duration
8      83
5      82
10     81
6      81
11     81
       ..
393     1
244     1
208     1
431     1
416     1
Name: count, Length: 257, dtype: int64


Sales 
 Sales
20.00     225
10.00     163
22.00      79
252.85     60
216.00     59
         ... 
171.00      1
159.00      1
177.00      1
1.99        1
287.40      1
Name: count, Length:

In [ ]:
ins_df.columns

Index(['Age', 'Agency_Code', 'Type', 'Commision', 'Channel', 'Duration',
       'Sales', 'Destination', 'Claimed', 'Product_Name', 'Claimed_Amount'],
      dtype='object')

In [ ]:
ins_df.shape

(3000, 11)

In [ ]:
# Get the proportions
print(ins_df.Claimed_Amount.value_counts(normalize=True))


Claimed_Amount
0       0.692000
5281    0.001333
4184    0.001000
4376    0.001000
4403    0.001000
          ...   
4683    0.000333
5064    0.000333
5501    0.000333
5592    0.000333
4547    0.000333
Name: proportion, Length: 749, dtype: float64


In [ ]:
for feature in ins_df.columns:
    if ins_df[feature].dtype == 'object':
        print('\n')
        print('feature:',feature)
        print(pd.Categorical(ins_df[feature].unique()))
        print(pd.Categorical(ins_df[feature].unique()).codes)
        ins_df[feature] = pd.Categorical(ins_df[feature]).codes



feature: Agency_Code
['C2B', 'EPX', 'CWT', 'JZI']
Categories (4, object): ['C2B', 'CWT', 'EPX', 'JZI']
[0 2 1 3]


feature: Type
['Airlines', 'Travel Agency']
Categories (2, object): ['Airlines', 'Travel Agency']
[0 1]


feature: Channel
['Online', 'Offline']
Categories (2, object): ['Offline', 'Online']
[1 0]


feature: Destination
['ASIA', 'Americas', 'EUROPE']
Categories (3, object): ['ASIA', 'Americas', 'EUROPE']
[0 1 2]


feature: Claimed
['No', 'Yes']
Categories (2, object): ['No', 'Yes']
[0 1]


feature: Product_Name
['Customised Plan', 'Cancellation Plan', 'Bronze Plan', 'Silver Plan', 'Gold Plan']
Categories (5, object): ['Bronze Plan', 'Cancellation Plan', 'Customised Plan', 'Gold Plan',
                         'Silver Plan']
[2 1 0 4 3]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
print('Age \n',ins_df.Age.value_counts())
print('\n')
print('Agency_Code \n',ins_df.Agency_Code.value_counts())
print('\n')
print('Type \n',ins_df.Type.value_counts())
print('\n')

print('Commision \n',ins_df.Commision.value_counts())
print('\n')
print('Channel \n',ins_df.Channel.value_counts())
print('\n')
print('Duration \n',ins_df.Duration.value_counts())
print('\n')
print('Sales \n',ins_df.Sales.value_counts())
print('\n')
print('Claimed_Amount \n',ins_df.Claimed_Amount.value_counts())
print('\n')
print('Destination \n',ins_df.Destination.value_counts())
print('\n')
print('Product_name \n',ins_df.Product_Name.value_counts())
print('\n')

Age 
 Age
36    999
31    125
48    108
30     96
35     94
     ... 
8       1
84      1
83      1
15      1
11      1
Name: count, Length: 70, dtype: int64


Agency_Code 
 Agency_Code
2    1365
0     924
1     472
3     239
Name: count, dtype: int64


Type 
 Type
1    1837
0    1163
Name: count, dtype: int64


Commision 
 Commision
0.00     1366
63.21      62
23.76      61
54.00      61
17.82      57
         ... 
49.40       1
68.08       1
15.56       1
1.25        1
13.50       1
Name: count, Length: 324, dtype: int64


Channel 
 Channel
1    2954
0      46
Name: count, dtype: int64


Duration 
 Duration
8      83
5      82
10     81
6      81
11     81
       ..
393     1
244     1
208     1
431     1
416     1
Name: count, Length: 257, dtype: int64


Sales 
 Sales
20.00     225
10.00     163
22.00      79
252.85     60
216.00     59
         ... 
171.00      1
159.00      1
177.00      1
1.99        1
287.40      1
Name: count, Length: 380, dtype: int64


Claimed_Amount 
 Claime

In [ ]:
ins_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             3000 non-null   int64  
 1   Agency_Code     3000 non-null   int8   
 2   Type            3000 non-null   int8   
 3   Commision       3000 non-null   float64
 4   Channel         3000 non-null   int8   
 5   Duration        3000 non-null   int64  
 6   Sales           3000 non-null   float64
 7   Destination     3000 non-null   int8   
 8   Claimed         3000 non-null   int8   
 9   Product_Name    3000 non-null   int8   
 10  Claimed_Amount  3000 non-null   int64  
dtypes: float64(2), int64(3), int8(6)
memory usage: 134.9 KB


In [ ]:
ld_df = ins_df

In [ ]:
X = ld_df.drop("Claimed_Amount", axis=1)



y = ld_df.pop("Claimed_Amount")

X.head()


Age  Agency_Code  Type  Commision  Channel  Duration  Sales  Destination  \
0   48            0     0       0.70        1         7   2.51            0   
1   36            2     1       0.00        1        34  20.00            0   
2   39            1     1       5.94        1         3   9.90            1   
3   36            2     1       0.00        1         4  26.00            0   
4   33            3     0       6.30        1        53  18.00            0   

   Claimed  Product_Name  
0        0             2  
1        0             2  
2        0             2  
3        0             1  
4        0             0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train, y_test= train_test_split(X, y, test_size=.30, random_state=1)


In [ ]:
print('X_train',X_train.shape)
print('X_test',X_test.shape)


print('Total Obs',2100+900)

X_train (2100, 10)
X_test (900, 10)
Total Obs 3000


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train = sc.fit_transform(X_train)

In [ ]:
x_train

array([[-0.19192502,  0.72815922,  0.80520286, ..., -0.43926017,
        -0.65391152,  0.24642411],
       [-0.19192502,  0.72815922,  0.80520286, ...,  1.27851702,
        -0.65391152,  0.24642411],
       [-0.97188154, -1.28518425, -1.24192306, ..., -0.43926017,
         1.52925889,  1.83381865],
       ...,
       [-0.19192502,  0.72815922,  0.80520286, ..., -0.43926017,
        -0.65391152,  0.24642411],
       [ 0.58803151,  1.73483096, -1.24192306, ..., -0.43926017,
        -0.65391152, -1.34097044],
       [-0.19192502, -1.28518425, -1.24192306, ..., -0.43926017,
        -0.65391152,  1.83381865]])

In [ ]:
# Apply the transformation on the test data
x_test = sc.transform(X_test)

In [ ]:
x_test

array([[-1.55684893, -0.27851251,  0.80520286, ...,  2.99629421,
        -0.65391152, -1.34097044],
       [ 1.66047173, -1.28518425, -1.24192306, ..., -0.43926017,
         1.52925889, -1.34097044],
       [-0.87438698, -1.28518425, -1.24192306, ..., -0.43926017,
         1.52925889, -1.34097044],
       ...,
       [-0.19192502, -1.28518425, -1.24192306, ..., -0.43926017,
         1.52925889, -1.34097044],
       [ 1.07550434,  1.73483096, -1.24192306, ..., -0.43926017,
        -0.65391152, -1.34097044],
       [-0.28941958,  1.73483096, -1.24192306, ..., -0.43926017,
        -0.65391152, -1.34097044]])

**Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression
lgs = LinearRegression()

In [ ]:
lgs.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred1 = lgs.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
r2 = r2_score(y_test, y_pred1)
print('r2 score =', r2)

mse = mean_squared_error(y_test, y_pred1)
print("Mean Square Error = ",mse)

mae = metrics.mean_absolute_error(y_test, y_pred1)
print("Mean Absolute Error = ", mae)

r2 score = 0.9876798942246776
Mean Square Error =  62994.61146949523
Mean Absolute Error =  157.63771176074613


**Ridge Regression**

In [ ]:

from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

ridge_regressor = Ridge(alpha=10)
ridge_regressor.fit(x_train, y_train)

y_pred2 = ridge_regressor.predict(x_test)

mse = mean_squared_error(y_test, y_pred2)
r2 = r2_score(y_test, y_pred2)


mae = metrics.mean_absolute_error(y_test, y_pred2)

print("Mean Absolute Error = ", mae)
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")




Mean Absolute Error =  156.7126930999803
Mean Squared Error: 62543.717796621306
R^2 Score: 0.9877680772869054


In [ ]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)


alpha_values = [0.1, 1, 10, 100]


ridge_reg = Ridge()


param_grid = {'alpha': alpha_values}
grid_search = GridSearchCV(estimator=ridge_reg, param_grid=param_grid,
                           scoring='neg_mean_squared_error', cv=5, verbose=1, n_jobs=-1)


grid_search.fit(X_train, y_train)


print("Best alpha parameter:", grid_search.best_params_)
print("Best CV score:", grid_search.best_score_)


best_ridge = grid_search.best_estimator_
y_pred = best_ridge.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R^2 Score:", r2)


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best alpha parameter: {'alpha': 0.1}
Best CV score: -56365.278059947574
Mean Absolute Error (MAE): 157.59035840277903
Mean Squared Error (MSE): 62965.42748878395
R^2 Score: 0.9876856018514242


**Lasso Regression**

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X_train, y_train)
y_pred_lasso = lasso_reg.predict(X_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)

print("Mean Absolute Error (MAE):", mae_lasso)
print("Mean Squared Error (MSE):", mse_lasso)
print("R^2 Score:", r2_lasso)


Mean Absolute Error (MAE): 157.60929666348417
Mean Squared Error (MSE): 62988.031820402066
R^2 Score: 0.9876811810327221


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

param_grid = {'alpha': [0.01, 0.1, 1, 10, 100]}

lasso = Lasso()

grid_search = GridSearchCV(estimator=lasso, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')

grid_search.fit(X_train, y_train)

best_lasso = grid_search.best_estimator_

y_pred_lasso = best_lasso.predict(X_test)

mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)

print("Best alpha: ", grid_search.best_params_['alpha'])
print("Mean Absolute Error (MAE):", mae_lasso)
print("Mean Squared Error (MSE):", mse_lasso)
print("R^2 Score:", r2_lasso)


Best alpha:  0.01
Mean Absolute Error (MAE): 157.63486930603983
Mean Squared Error (MSE): 62993.86579104595
R^2 Score: 0.9876800400599667


**Random Forest Regressor**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfg3 = RandomForestRegressor()
rfg3.fit(X_train, y_train)
y_pred3 = rfg3.predict(x_test)

mse = mean_squared_error(y_test, y_pred3)
r2 = r2_score(y_test, y_pred3)


mae = metrics.mean_absolute_error(y_test, y_pred3)

print("Mean Absolute Error = ", mae)
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")




Mean Absolute Error =  212.75881111111113
Mean Squared Error: 225175.44184722225
R^2 Score: 0.9559615466013929


**MLPRegressor**

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

mlp_regressor = MLPRegressor(hidden_layer_sizes=(100,), alpha=0.0001, random_state=1, max_iter=1000)
mlp_regressor.fit(X_train, y_train)
y_pred_mlp = mlp_regressor.predict(X_test)

mse_mlp = mean_squared_error(y_test, y_pred_mlp)
r2_mlp = r2_score(y_test, y_pred_mlp)
mae_mlp = mean_absolute_error(y_test, y_pred_mlp)

print("Mean Absolute Error (MAE):", mae_mlp)
print("Mean Squared Error (MSE):", mse_mlp)
print("R^2 Score:", r2_mlp)


Mean Absolute Error (MAE): 242.64817812945887
Mean Squared Error (MSE): 141621.14701622733
R^2 Score: 0.9723025911175387


In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Age           3000 non-null   int64  
 1   Agency_Code   3000 non-null   int8   
 2   Type          3000 non-null   int8   
 3   Commision     3000 non-null   float64
 4   Channel       3000 non-null   int8   
 5   Duration      3000 non-null   int64  
 6   Sales         3000 non-null   float64
 7   Destination   3000 non-null   int8   
 8   Claimed       3000 non-null   int8   
 9   Product_Name  3000 non-null   int8   
dtypes: float64(2), int64(2), int8(6)
memory usage: 111.5 KB


In [ ]:
new_data = np.array([[35, 1, 1, 4.6, 1, 18, 2.51, 0, 1,1]])


predicted_claimed_amount = best_ridge.predict(new_data)

print("Predicted Claimed Amount:", predicted_claimed_amount)

Predicted Claimed Amount: [4547.14744666]
